### PR TITLE
multiple fit iterations - clustering refactoring - unit test 

### PR DESCRIPTION
**Pull request by mallibus**
I'm opening this new pull request with target scope of adding num_iter parameter to DTWKmeans API.
While doing so I'm adding unit tests for the new features and some refactoring of the original clustering.py
Please keep this pull request open until completed: we can use it to comment commits on the way, and it is useful to keep track of possible merge conflicts.

The first commit includes computation of inertia and some refactoring

### CODE REVIEW

**Comment by mallibus** [comment]
Hi, inertia concept and num_init argument in DTWKMeans are now integrated in pynuTS, with tests and a new demo notebook to explain the inertia concept. 
next:

1.  In the new demo notebook I'll add soon or late a demo of the elbow method to select the number of clusters.
2. I am not planning to change the clustering API any more, however some refactoring could still be beneficial.
3. Finally, I'd like to integrate the function `get_clustered_list` in some python file instead of duplicating it across the demo notebooks. The question is either to integrate it in the pynuTS library or to keep it segregated in the demo folder maybe in a demo_utils.py

**Comment by nickprock** [comment]
Thanks @mallibus I wait for your green light to integrate everything 🙂

**Comment by mallibus** [comment]
Hi @nickprock  if you approve the changes you can integrate.
1. elbow method demo added (it can be improved with a more interesting dataset but for now will do)
2. no refactoring added ... it will wait for better times
3. `get_clustered_list` integrated in a dedicated file to avoid repeating it in all demos.

**Comment by nickprock** [comment]
Thanks @mallibus I merge your update and as soon as possible I update the readme with versione upgrade. 👍

**Comment by mallibus** [comment]
Perfect. When done you can also close the issue about the local minima😉

Il Mar 9 Mar 2021, 18:09 Nicola Procopio <notifications@github.com> ha
scritto:

**Pull request merged**
