### PR TITLE
First dev version of ARIMA generator

### PR DESCRIPTION
**Pull request by mallibus**
Hi Nicola, here is a first drop of the ARIMA generator with a demo notebook. For now both code and demo notebook are in the demo folder as I'd like still to integrate all the generation functions used in the other demo in the generator module before submitting it for the main library.
Still I'd like to get feedback before going too far.

### CODE REVIEW

**Comment by mallibus** [comment]
Sorry I found a bug in the I part of the ARIMA generator, please wait before integrating to dev

**Comment by nickprock** [comment]
Don't worry, I wait your ok to integrate. 😉

**Comment by nickprock** [comment]
@mallibus can I merge?

**Comment by mallibus** [comment]
Go! Still a lot of improvememts to do but at least this piece works fine

**Pull request merged**
