### PR TITLE
Bugfixes in SAX encoding demo notebook

### PR DESCRIPTION
**Pull request by mallibus**
1) Fixed import from parent folder see [relevant issue](https://github.com/nickprock/pynuTS/issues/13)

2) Fixed X DataFrame [orientation issue](https://github.com/nickprock/pynuTS/issues/15) and added  time series with inverted param to expose the anomaly

### CODE REVIEW

**Comment by nickprock** [comment]
Thanks @mallibus I can check the conflicts on monday. 😉

**Review by nickprock — APPROVED** [review]

**Comment by nickprock** [comment]
Hi @mallibus , could you sendi me a pull request only for SAX test? Thanks

**Comment by nickprock** [comment]
Hi @mallibus , I merge your test file to dev and main branch

**Comment by mallibus** [comment]
hi yes  I committed the test file in this [commit](https://github.com/nickprock/pynuTS/commit/b66eef75c31c641a9b30d04433b4c6d44f7d9add).

Sorry for mixing it with the other stuff... next time I may create a branch for the fixes and one for the dev / test.
By the way I have some comments on the SAX code, check our private chat on discord.

**Pull request closed without merging**
